apiVersion: apps/v1
kind: Deployment
metadata:
  name: fase4apipod
  labels:
    app: fase4apipod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fase4apipod
  template:
    metadata:
      labels:
        app: fase4apipod
    spec:
      containers:
      - name: fase4apipod
        image: pdaguis/fase4-api:latest
        ports:
        - containerPort: 4000
  
---

apiVersion: v1
kind: Service
metadata:
  name: fase4api-service
spec:
  selector:
    app: fase4apipod
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 9376
  type: LoadBalancer